### ISSUE TITLE
Add target vmaf option

### ISSUE THREAD

**Issue by EitanMM** [gianni-rosato/rAV1ator#4]
One of the best features of av1an is the ability to set a vmaf target, it's only natural that rav1ator would embrace it being based on av1an

**Comment by gianni-rosato** [comment]
I do not think this feature is valuable. A lot of time is wasted in convexhull encoding setups targeting VMAF; I'd prefer to use XPSNR for such a feature, and currently I think most users are better off utilizing SVT-AV1-PSY's various features to improve consistency as opposed to something like this.

**Comment by thepragmaticmero** [comment]
tutorial on XPSNR pls? for the newbies~

**Comment by gianni-rosato** [comment]
https://github.com/gianni-rosato/sxpsnr

This might help - otherwise there is an FFmpeg plugin that requires patching FFmpeg. 

sxpsnr only works with raw streams or Y4m
