### ISSUE TITLE
md5sum warning when the command is located on ~/.local/bin/rav1ator-cli

### ISSUE THREAD

**Issue by thepragmaticmero** [gianni-rosato/rAV1ator#5]
```
$ rav1ator-cli --help
md5sum: /usr/local/bin/rav1ator-cli: No such file or directory
rAV1ator: CLI Edition_ v0.3.0

Usage:
        rav1ator-cli [input] [output] [--offline]
...
```
It's hard coded I suppose, maybe change md5sum location to $PATH instead of `/usr/local/bin/rav1ator-cli`

**Comment by gianni-rosato** [comment]
Thanks for the issue request. I might retire development of rAV1ator CLI soon to be honest - the codebase is kind of a mess and I'm seeing Av1an become less useful as SVT-AV1-PSY matures and scene detection is increasingly less impactful. This is an important point though and I'll look into it in the future, but probably low priority

**Comment by thepragmaticmero** [comment]
sad to hear :C keep up the good work then~

**Comment by gianni-rosato** [comment]
If enough people are interested, I'll keep it up, but I don't see a ton of users.

Also, this is the `rAV1ator` repo - there's another repo for `rav1ator-cli` :)

**Comment by thepragmaticmero** [comment]
LOL my bad xD I was on RTS gaming keyboard typing mode. I missread the repo XD. I'll see if I could become a maintainer~
